FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /App
EXPOSE 8080
EXPOSE 8081


FROM mcr.microsoft.com/dotnet/sdk:8.0 as build

ARG BUILD_CONFIGURATION=Release

WORKDIR /src

COPY . .
RUN dotnet restore "FormulariosDinamicos.csproj"
RUN dotnet build "FormulariosDinamicos.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "FormulariosDinamicos.csproj" -c $BUILD_CONFIGURATION -o /app/publish

FROM base AS final
# Build runtime image
WORKDIR /src
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FormulariosDinamicos.dll"]