version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234

    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql

  formsAPI:
    depends_on:
      - db
    image: jorgesolerrr/dynamic-forms
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DBHOST=db


    

# Names our volume
volumes:
  my-db: